# Generated by Django 2.0.6 on 2018-07-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=300)),
                ('genre', models.CharField(default='none', max_length=100)),
                ('cast', models.CharField(default='none', max_length=500)),
                ('director', models.CharField(default='none', max_length=50)),
                ('year', models.CharField(default='none', max_length=4)),
                ('country', models.CharField(default='none', max_length=20)),
                ('comment', models.CharField(default='no comment', max_length=1000)),
                ('rating', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
